config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls', namespace='portfolio')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Mubarak Admin"
admin.site.site_title = "Mubarak Admin Portal"
admin.site.index_title = "Welcome to Mubarak Admin Portal"

handler500 = 'config.urls.handler500_view'


def handler500_view(request, *args, **argv):
    import traceback
    print(traceback.print_exc())
    return render(request, 'error/500.html', status=500)

portfolio/urls.py
from django.urls import path
from .views import (
    portfolio_view,
    projects_view,
    contact_view,
    resume_download_view,
    send_email_view
)

app_name = 'portfolio'

urlpatterns = [
    path('', portfolio_view, name='portfolio-page'),
    path('projects/', projects_view, name='projects-page'),
    path('contact/', contact_view, name='contact-page'),
    path('resume/', resume_download_view, name='resume'),
    path('send-email/', send_email_view, name='send-email'),
]

portfolio/models.py
from django.db import models


class VisitorDetails(models.Model):
    ip = models.CharField(max_length=20, blank=True, null=True)
    last_visited = models.DateTimeField(null=True, blank=True)
    visited_count = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Visitor Details'

    def __str__(self):
        return self.ip

user_management/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views import View
from django.http import FileResponse
import os


class Portfolio(View):

    def get(self, request):
        context = {
            'title': 'Mubarak Portfolio',
            'nb': 'portfolio',
        }
        return render(self.request, 'portfolio/portfolio.html', context)


portfolio_view = Portfolio.as_view()


class Projects(View):
    def get(self, request):
        context = {
            'title': 'Mubarak Projects',
            'nb': 'projects',
        }
        return render(self.request, 'portfolio/projects.html', context)


projects_view = Projects.as_view()


class Contact(View):
    def get(self, request):
        context = {
            'title': 'Mubarak Contact',
            'nb': 'contact',
        }
        return render(self.request, 'portfolio/contact.html', context)


contact_view = Contact.as_view()


class ResumeDownload(View):
    RESUME_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'media', 'resume',
                               'Mubarak_Ali.pdf')

    def get(self, request):
        return FileResponse(open(self.RESUME_PATH, 'rb'), content_type='application/pdf')


resume_download_view = ResumeDownload.as_view()


class SendEmail(View):
    def post(self, request):
        data = self.request.POST
        if check := self.send_app_email(data):
            messages.success(self.request, 'Email sent successfully')
        else:
            messages.error(self.request, 'Email not sent')
        return render(self.request, 'portfolio/contact.html', {'title': 'Mubarak Contact', 'nb': 'contact'})

    @staticmethod
    def send_app_email(data):
        from django.core.mail import send_mail
        from django.conf import settings
        try:
            subject = f'New message from portfolio website from {data.get("name")}'
            message = f'Name: {data.get("name")}\nEmail: {data.get("email")}\nMessage: {data.get("message")}'
            email_from = settings.EMAIL_HOST_USER
            recipient_list = ['alimubarak9915@gmail.com']
            check = send_mail(subject, message, email_from, recipient_list)
            return check == 1
        except Exception as e:
            import traceback
            print(traceback.format_exc())
            print(e)


send_email_view = SendEmail.as_view()

user_management/views.py
from django.shortcuts import render

# Create your views here.

portfolio/templates/portfolio/contact.html
{% extends 'base.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row my-3">
            {% include 'components/alert.html' %}
        </div>
    </div>
    <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
        <div class="card shadow-custom w-100">
            <div class="card-body">
                <h4 class="text-center" style="color: yellow;letter-spacing: 2px">CONTACT ME</h4>
                <hr>
                <form action="{% url 'portfolio:send-email' %}" method="post" autocomplete="off">
                    {% csrf_token %}
                    <!-- Name input -->
                    <div class="form-outline mb-4">
                        <input type="text" name="name" id="name" class="form-control" required/>
                        <label class="form-label" for="name">Name</label>
                    </div>

                    <!-- Email input -->
                    <div class="form-outline mb-4">
                        <input type="email" name="email" id="email" class="form-control" required/>
                        <label class="form-label" for="email">Email address</label>
                    </div>

                    <!-- Message input -->
                    <div class="form-outline mb-4">
                        <textarea name="message" class="form-control" id="message" rows="4" required></textarea>
                        <label class="form-label" for="message">Message</label>
                    </div>

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-white btn-block mb-4">Send</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

portfolio/templates/portfolio/portfolio.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row d-flex align-items-center justify-content-center" style="min-height: 80vh">
            <div class="col-lg-6 text-center">
                <h1 style="letter-spacing: 6px">MUBARAK ALI <br>
                    <p style="font-size: 22px;letter-spacing: 1px" class="mt-2 fw-lighter">&#8608; PYTHON DEVELOPER
                        &#8606;</p></h1>
                <a href="{% url 'portfolio:resume' %}" class="btn btn-white" target="_blank">download resume</a>
            </div>
            <div class="col-lg-4 text-center">
                <img class="rounded-circle shadow-4-strong img-fluid" alt="avatar2"
                     src="{% static 'img/mubarak.png' %}" style="width: 450px"/>
            </div>
        </div>
        <hr class="text-white mt-0">
        <div class="row">
            <div class="col-lg-3 my-3"></div>
            <div class="col-lg-6 my-3 text-center">
                <h2 class="mb-3" style="letter-spacing: 2px"><span style="color: yellow">&#8609;</span> ABOUT ME <span
                        style="color: yellow">&#8609;</span></h2>
                <p class="fw-light" style="letter-spacing: 1px">
                    As a Python developer, I have a passion for writing clean, efficient, and well-documented code. 
                    I am well-versed in Python programming language and its libraries and frameworks such as Django, 
                    Flask, Django Rest Framework, and FastAPI. I am enthusiastic about working in a team environment 
                    and contributing my skills to create impactful projects. I am a quick learner and adapt easily to 
                    new technologies and tools. I am eager to learn and grow in a dynamic and challenging work environment 
                    that encourages creativity, innovation, and continuous learning. If you're looking for a dedicated and 
                    passionate Python developer, I am the right candidate for you.    
                </p>
            </div>
            <div class="col-lg-3 my-3"></div>
        </div>
        <hr class="text-white mt-0">
        <div class="row my-3" style="letter-spacing: 2px">
            <h2 class="mb-4 text-center" style="letter-spacing:2px"><span style="color: yellow">&#8609;</span> SKILLS
                <span style="color: yellow">&#8609;</span></h2>
            <div class="col-lg-4 text-center">
                <h4 class="" style="color: yellowgreen">FrontEnd</h4>
                <h6>&#8608; HTML</h6>
                <h6>&#8608; CSS</h6>
                <h6>&#8608; JavaScript</h6>
            </div>
            <div class="col-lg-4 text-center">
                <h4 class="" style="color: yellowgreen">Backend</h4>
                <h6>&#8608; Python</h6>
                <h6>&#8608; Django</h6>
                <h6>&#8608; Django Rest Framework</h6>
            </div>
            <div class="col-lg-4 text-center">
                <h4 class="" style="color: yellowgreen">Devops</h4>
                <h6>&#8608; Docker</h6>
                <h6>&#8608; GitLab</h6>
                <h6>&#8608; AWS</h6>
            </div>
        </div>
    </div>
{% endblock %}

portfolio/templates/portfolio/projects.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row mx-2 my-4">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title" style="letter-spacing: 2px">Get Popular SMM Panel <a href="https://getpopular-production-95a6.up.railway.app/user/login/?next=/" target="_blank"><i class="fa-solid fa-link text-success"></i></a></h5>
                        <p class="card-text" style="font-weight: lighter;letter-spacing: 2px">An SMM panel is a service
                            that allows you to purchase social media
                            followers, likes, and views for your business. It can be a great way to boost your online
                            presence and help you grow your business. By using an SMM panel, you can get the followers,
                            likes, and views you need quickly and easily.</p>
                        <hr>
                        <div class="row">
                            <div class="col-lg-2 my-2">
                                <a href="{% static 'projects/get_popular_img_1.png' %}" data-lightbox="project_1" class="zoom-gallery">
                                    <img src="{% static 'projects/get_popular_img_1.png' %}" alt="get_popular_img_1"
                                         class="img-thumbnail">
                                </a>
                            </div>
                            <div class="col-lg-3 my-2">
                                <a href="{% static 'projects/get_popular_img_2.png' %}" data-lightbox="project_1" class="zoom-gallery">
                                    <img src="{% static 'projects/get_popular_img_2.png' %}" alt="get_popular_img_2"
                                         class="img-thumbnail">
                                </a>
                            </div>
                            <div class="col-lg-3 my-2">
                                <a href="{% static 'projects/get_popular_img_3.png' %}g" data-lightbox="project_1" class="zoom-gallery">
                                    <img src="{% static 'projects/get_popular_img_3.png' %}" alt="get_popular_img_3"
                                         class="img-thumbnail">
                                </a>
                            </div>
                            <div class="col-lg-3 my-2">
                                <a href="{% static 'projects/get_popular_img_4.png' %}" data-lightbox="project_1" class="zoom-gallery">
                                    <img src="{% static 'projects/get_popular_img_4.png' %}" alt="get_popular_img_4"
                                         class="img-thumbnail">
                                </a>
                            </div>
                            <div class="col-lg-3 my-2">
                                <a href="{% static 'projects/get_popular_img_5.png' %}" data-lightbox="project_1" class="zoom-gallery">
                                    <img src="{% static 'projects/get_popular_img_5.png' %}" alt="get_popular_img_5"
                                         class="img-thumbnail">
                                </a>
                            </div>
                            <div class="col-lg-3 my-2">
                                <a href="{% static 'projects/get_popular_img_6.png' %}" data-lightbox="project_1" class="zoom-gallery">
                                    <img src="{% static 'projects/get_popular_img_6.png' %}" alt="get_popular_img_6"
                                         class="img-thumbnail">
                                </a>
                            </div>
                            <div class="col-lg-3 my-2">
                                <a href="{% static 'projects/get_popular_img_7.png' %}" data-lightbox="project_1" class="zoom-gallery">
                                    <img src="{% static 'projects/get_popular_img_7.png' %}" alt="get_popular_img_7"
                                         class="img-thumbnail">
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true
        });
    </script>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.dark.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block navbar %}{% include 'components/navbar.html' %}{% endblock %}
<div style="min-height: 100vh">{% block content %} {% endblock %}</div>
<!------------------------------MODAL----------------------------->
<div class="modal top fade" id="visitor-info" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
     data-mdb-backdrop="static" data-mdb-keyboard="true">
    <div class="modal-dialog modal-sm ">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Visitor Info</h5>
                <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body fw-light" style="letter-spacing: 1px">
                <h5>Your IP: <span style="color: yellow">{{ visitor.ip }}</span></h5>
                <h6>Last Visited date: <span style="color: yellow">{{ visitor.last_visited|date }}</span></h6>
                <h6>Last Visited Time: <span style="color: yellow">{{ visitor.last_visited|time }}</span></h6>
                <h6>Your Total Visits: <span style="color: yellow">{{ visitor.visited_count }}</span></h6>
            </div>
        </div>
    </div>
</div>
<!------------------------------MODAL----------------------------->
{% block footer %}{% include 'components/footer.html' %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-zoom/1.7.21/jquery.zoom.js"
        integrity="sha512-LjDU5V5K+EixYXzTBmWnQPPLZXTUNJOfwB0UPnFqbPeoUl2/N/AKPJAYVuNNmMv9RZeGZXRwu4PDI37GCRuOTQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'js/lightbox.js' %}"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $('#msg').hide();
        }, 3000);
    });

</script>
{% block js %}{% endblock %}
</body>
</html>

templates/components/alert.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-1 h6" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/components/footer.html
<footer class="text-center text-white" style="background-color: #424242">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © {% now 'Y' %} Copyright:
    <a class="text-white" href="/">MUBARAK ALI</a>
  </div>
</footer>

templates/components/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #424242">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'img/letter-m.png' %}" alt="logo" style="width: 40px" class="rounded-circle">
        </a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:portfolio-page' %}" style="letter-spacing: 1px;{% if nb == 'portfolio' %}color: yellow {% endif %}">PORTFOLIO</a>
                </li>
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:services-page' %}" style="letter-spacing: 1px;{% if nb == 'services' %}color: yellow {% endif %}">SERVICES</a>
                </li> {% endcomment %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:projects-page' %}" style="letter-spacing: 1px;{% if nb == 'projects' %}color: yellow {% endif %}">PROJECTS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:contact-page' %}" style="letter-spacing: 1px;{% if nb == 'contact' %}color: yellow {% endif %}">CONTACT ME</a>
                </li>
            </ul>
            <ul class="navbar-nav d-flex flex-row ms-auto me-3">
                <li class="nav-item">
                    <a class="nav-link active" href="#" style="color: yellow" data-mdb-toggle="modal" data-mdb-target="#visitor-info">&#10547;Total Visitors ({{ count }})</a>
                </li>
            </ul>
        </div>
    </div>
</nav>